import BeanSlider from '@/components/home/beanSlider/BeanSlider'
import Blogs from '@/components/home/blogs/Blogs';
import BrazilCoffee from '@/components/home/Brazil/BrazilCoffee';
import HandPicked from '@/components/home/handPicked/HandPicked';
import Head from 'next/head'
import Slider from '@/components/home/top-slider/Slider'
import Sponsors from '@/components/home/sponsors/Sponsors';
import Testimonials from '@/components/home/testimonials/Testimonials';
import Trending from '@/components/home/trending/Trending';
import axios from 'axios';

export default function Home({productsList}) {
  
  return (
    <>
      <Head>
        <title>coffee store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Slider />
        <BeanSlider />
        <HandPicked productsList={productsList}/>
        <BrazilCoffee />
        <Trending />
        <Testimonials />
        <Sponsors />
        <Blogs />
      </main>
    </>
  )
}

export const getServerSideProps = async () => {
  const res = await axios.get('http://localhost:3000/api/products');
  
  return {
    props: {
      productsList: res.data
    }
  }
}